name: ccdown
dependencies:
  - python=3.7
  #
  - ipython
  #
  - dask-core
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - tensorflow=1.14.0
  - xarray
  #
  - pip
  - pip:
    - https://github.com/joshloyal/sliced/archive/243bde2.zip
